-- Bootstrap all workspace custom modules.
-- Runs after plugins/ui.lua so icons and theme are already active.

require('workspace.repos').setup()
require('workspace.tabline').setup()
require('workspace.filetree').setup()
require('workspace.statusline').setup()
require('workspace.winbar').setup()
require('workspace.dirdash').setup()
require('workspace.workspace').setup()
require('workspace.home').setup()
require('workspace.tasks').setup()
require('workspace.outline').setup()
require('workspace.funcnav').setup()
require('workspace.gotofile').setup()
require('workspace.mdpreview').setup()
require('workspace.zen').setup()
require('workspace.mdtoc').setup()
require('workspace.json_tools').setup()
require('workspace.search').setup()
require('workspace.sidebar').setup()
require('workspace.notify').setup()
require('workspace.marks').setup()
require('workspace.palette').setup()
require('workspace.git_ui').setup()
require('workspace.claude.codegen').setup()
require('workspace.claude.fix').setup()
require('workspace.claude.assist').setup()
require('workspace.test_ui').setup()
require('workspace.templates').setup()
